language: python
python:
  - "3.4"
services:
  - redis-server
  - postgresql
# command to install dependencies
before_install:
  - cd server/
  - openssl aes-256-cbc -K $encrypted_788c8f248cb4_key -iv $encrypted_788c8f248cb4_iv -in local_settings.py.enc -out server/local_settings.py -d
install:
  - pip install -r pip_install.txt
# command to run tests
script:
  - python manage.py cold_test app.cold_tests.SimpleTest -v2
  - python manage.py test --noinput --setting=server.custom_settings.travis_ci_settings -v2
before_deploy:
  - openssl aes-256-cbc -K $encrypted_788c8f248cb4_key -iv $encrypted_788c8f248cb4_iv -in dev_deploy.key.enc -out dev_deploy.key -d
  - chmod 600 dev_deploy.key
deploy:
  provider: script
  skip_cleanup: true
  script: ./dev_deploy.sh
  on:
    branch: master
after_deploy:
  - rm -f dev_deploy.key

