from django.conf.urls import include, url
from . import views


urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^login/$', views.login, name="login"),
    url(r'^login/auth/$', views.login_auth, name="login_auth"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^analysis$', views.AnalysisView.as_view(), name="analysis"),
    url(r'^students/$', views.StudentView.as_view(), name="students"),
    url(r'^students/schedule/manage/$', views.StudentScheduleManageView.as_view(), name="student_schedule_manage"),
    url(r'^students/schedule/changelog/$', views.StudentScheduleChangelogView.as_view(), name="student_schedule_changelog"),
    url(r'^students/schedule/action/$', views.StudentScheduleActionView.as_view(), name="student_schedule_action"),
    url(r'^teachers/$', views.TeacherView.as_view(), name="teachers"),
    url(r'^teachers/unpublished/$', views.TeacherUnpublishedView.as_view(), name="teachers_unpublished"),
    url(r'^teachers/published/$', views.TeacherPublishedView.as_view(), name="teachers_published"),
    url(r'^teachers/unpublished/(?P<tid>\d+)/edit$', views.TeacherUnpublishedEditView.as_view(), name="teachers_unpublished_edit"),
    url(r'^teachers/published/(?P<tid>\d+)/edit$', views.TeacherUnpublishedEditView.as_view(), name="teachers_published_edit"),
    url(r'^teachers/action/$', views.TeacherActionView.as_view(), name="teachers_action"),
    url(r'^teachers/bankcard/list/$', views.TeacherBankcardView.as_view(), name="teachers_bankcard_list"),
    url(r'^teachers/income/list/$', views.TeacherIncomeView.as_view(), name="teachers_income_list"),
    url(r'^teachers/income/(?P<tid>\d+)/detail/$', views.TeacherIncomeDetailView.as_view(), name="teachers_income_detail"),
    url(r'^teachers/withdrawal/list/$', views.TeacherWithdrawalView.as_view(), name="teachers_withdrawal_list"),
    url(r'^schools/$', views.SchoolsView.as_view(), name="schools"),
    url(r'^school/$', views.SchoolView.as_view(), name='staff_school'),
    url(r'^school/timeslot$', views.SchoolTimeslotView.as_view(), name='school_timeslot'),
    url(r'^orders/review/$', views.OrderReviewView.as_view(), name="orders_review"),
    url(r'^orders/refund/$', views.OrderRefundView.as_view(), name="orders_refund"),
    url(r'^orders/action/$', views.OrderRefundActionView.as_view(), name="orders_action"),
    url(r'^coupons/list/$', views.CouponsListView.as_view(), name="coupons_list"),
    url(r'^coupon/config/$', views.CouponConfigView.as_view(), name="coupon_config"),
    url(r'^evaluations/$', views.EvaluationView.as_view(), name="evaluations"),
    url(r'^evaluations/action/$', views.EvaluationActionView.as_view(), name="evaluations_action"),
    url(r'^level/price/config/$', views.LevelPriceConfigView.as_view(), name="level_price_cfg"),
    url(r'^level/salary/config/$', views.LevelSalaryConfigView.as_view(), name="level_salary_cfg"),
    url(r'^school/account/info/$', views.SchoolAccountInfoView.as_view(), name="school_account_info"),
    url(r'^school/price/config/$', views.SchoolPriceConfigView.as_view(), name="school_price_cfg"),
    url(r'^school/account/income/records/$', views.SchoolIncomeRecordView.as_view(), name="school_income_records"),
    url(r'^school/account/income/audit/$', views.SchoolIncomeAuditView.as_view(), name="school_income_audit"),
    url(r'^region/(?P<rid>\d+)/$', views.RegionView.as_view(), name="region_config"),
    url(r'^course/live-course/$', views.LiveCourseView.as_view(), name="live_course"),
    url(r'^course/live-course/classroom/$', views.CreateClassRoomView.as_view(), name="create_room"),
    url(r'^course/live-course/list/$', views.LiveCourseListView.as_view(), name="live_course_list"),
    url(r'^course/live-course/detail/(?P<cid>\d+)/$$', views.LiveCourseView.as_view(), name="live_course_detail"),
    url(r'^auth/$', views.StaffAuthView.as_view(), name="staff_auth"),
]
