inhibit_all_warnings!
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!
inhibit_all_warnings!

link_with 'teacher', 'parent', 'parentTests'
pod 'Alamofire', '~> 3.3.0'
pod 'SnapKit', '~> 0.20.0'
pod 'Kingfisher', '~> 2.2.0'
pod 'IQKeyboardManagerSwift', '~> 3.3.6'
pod 'DateTools', '~> 1.7.0'


pod 'UMengAnalytics-NO-IDFA'

pod 'Pingpp/Alipay', '~> 2.2.0'
pod 'Pingpp/Wx', '~> 2.2.0'

target 'teacher' do
end

target 'parent' do
    xcodeproj 'mala-ios', 'DevDebug' => :debug, 'DevRelease' => :release, 'PrdRelease' => :release
end

target 'parentTests' do
    xcodeproj 'mala-ios', 'DevDebug' => :debug, 'DevRelease' => :release, 'PrdRelease' => :release
end
