from django.contrib import admin

from .models import *


admin.site.register(Region)
admin.site.register(School)
admin.site.register(Grade)
admin.site.register(Subject)
admin.site.register(GradeSubject)
admin.site.register(Level)
admin.site.register(RegionGradeSubjectLevelPrice)
admin.site.register(Role)
admin.site.register(Person)
admin.site.register(Teacher)
admin.site.register(Certification)
admin.site.register(InterviewRecord)
admin.site.register(BankCard)
admin.site.register(BankCodeInfo)
admin.site.register(Balance)
admin.site.register(Withdraw)
admin.site.register(Feedback)
admin.site.register(Parent)
admin.site.register(Coupon)
admin.site.register(TimeSlot)
admin.site.register(RegionTimeSlot)
admin.site.register(Order)
admin.site.register(PlannedCourse)
admin.site.register(Comment)
admin.site.register(Message)
