# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Parent'),
        ),
    ]
