# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 13:18
from __future__ import unicode_literals

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_auto_20160130_1759'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
            ],
        ),
    ]
