# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_random_publish_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.TimeSlot'),
        ),
    ]
