# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_school'),
        ('app', '0066_auto_20160203_1039'),
    ]

    operations = [
    ]
