# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_auto_20160204_1249'),
        ('app', '0067_merge'),
    ]

    operations = [
    ]
