# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 13:13
from __future__ import unicode_literals

import app.utils.algorithm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_auto_20160216_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='charge_id',
            field=models.CharField(max_length=27),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=app.utils.algorithm.orderid, max_length=20, unique=True),
        ),
    ]
