# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_teacher_graduate_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='introduce',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='graduate_school',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
