# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 08:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def update_account_user(apps, schema_editor):
    Account = apps.get_model('app', 'Account')
    accounts = Account.objects.all()
    for acc in accounts:
        acc.user = acc.teacher.user
        acc.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0073_auto_20160217_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RunPython(update_account_user),
        migrations.RemoveField(
            model_name='account',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accounthistory',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accounthistory',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='accounthistory',
            name='bankcard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.BankCard'),
        ),
        migrations.AlterField(
            model_name='accounthistory',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accounthistory',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
