# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_auto_20160216_2113'),
        ('app', '0073_auto_20160217_1031'),
    ]

    operations = [
    ]
