# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_merge'),
        ('app', '0074_auto_20160217_1602'),
    ]

    operations = [
    ]
