# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_merge'),
        ('app', '0075_auto_20160217_1657'),
    ]

    operations = [
    ]
