# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
