# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberservice',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
