# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 03:52
from __future__ import unicode_literals

import datetime
from django.utils.timezone import make_aware
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_auto_20160217_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_start', models.DateTimeField(default=make_aware(datetime.datetime.now()))),
                ('expired_at', models.DateTimeField(default=make_aware(datetime.datetime.now()))),
                ('amount', models.PositiveIntegerField()),
                ('mini_course_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CouponRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='mini_course_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupon',
            name='validated_start',
            field=models.DateTimeField(default=make_aware(datetime.datetime.now())),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expired_at',
            field=models.DateTimeField(default=make_aware(datetime.datetime.now())),
        ),
    ]
