# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_auto_20160223_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_id', models.CharField(max_length=40)),
                ('created', models.DateTimeField()),
                ('livemode', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('refunded', models.BooleanField(default=False)),
                ('app', models.CharField(max_length=40)),
                ('channel', models.CharField(max_length=10)),
                ('order_no', models.CharField(max_length=20)),
                ('client_ip', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('amount_settle', models.IntegerField()),
                ('currency', models.CharField(max_length=5)),
                ('subject', models.CharField(max_length=20)),
                ('body', models.CharField(max_length=200)),
                ('extra', models.CharField(max_length=200)),
                ('time_paid', models.DateTimeField()),
                ('time_expire', models.DateTimeField()),
                ('time_settle', models.DateTimeField(blank=True, null=True)),
                ('transaction_no', models.CharField(max_length=50)),
                ('amount_refunded', models.IntegerField(default=0)),
                ('failure_code', models.CharField(max_length=10)),
                ('failure_msg', models.CharField(max_length=30)),
                ('metadata', models.CharField(max_length=50)),
                ('credential', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='charge_id',
        ),
        migrations.AddField(
            model_name='charge',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Order'),
        ),
    ]
