# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_auto_20160223_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='credential',
            field=models.CharField(max_length=200),
        ),
    ]
