# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_auto_20160223_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='ch_id',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
