# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_auto_20160223_1854'),
        ('app', '0080_merge'),
    ]

    operations = [
    ]
