# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_orderrefundrecords'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderRefundRecords',
            new_name='OrderRefundRecord',
        ),
    ]
