# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0088_teacher_recommended_on_wechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='commission_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='price',
            name='salary',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
