# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_wallet_test_data_fixtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-created_at']},
        ),
    ]
