# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_auto_20160301_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Level'),
        ),
    ]
