# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0093_auto_20160301_1047'),
        ('app', '0092_auto_20160227_1535'),
    ]

    operations = [
    ]
