# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkcode',
            name='block_start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
