# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0095_checkcode_block_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wx_openid',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
