# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0095_checkcode_block_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='channel',
            field=models.CharField(max_length=20),
        ),
    ]
