# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0095_checkcode_block_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(blank=True, choices=[('rp', '退费审核中'), ('ra', '退费成功'), ('rr', '退费被驳回')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('u', '待付款'), ('p', '已付款'), ('d', '已取消'), ('r', '退费成功')], default='u', max_length=2),
        ),
        migrations.AlterField(
            model_name='orderrefundrecord',
            name='status',
            field=models.CharField(choices=[('rp', '退费审核中'), ('ra', '退费成功'), ('rr', '退费被驳回')], default='rp', max_length=2),
        ),
    ]
