# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0096_auto_20160301_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrefundrecord',
            name='refund_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderrefundrecord',
            name='refund_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderrefundrecord',
            name='remaining_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
