# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0097_auto_20160302_2255'),
        ('app', '0096_auto_20160302_2127'),
    ]

    operations = [
    ]
