# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0097_test_confirm_some_timeslot'),
        ('app', '0098_merge'),
    ]

    operations = [
    ]
