# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0099_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
