# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0100_order_refund_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeiXinToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
