# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 20:15
from __future__ import unicode_literals

from django.db import migrations, models

def unpublished_test_teacher(apps, schema_editor):
    """
    旧的测试老师默认published=True, 把状态不是面试通过(4)的TEST老师, 改成未发布
    """
    Teacher = apps.get_model('app', 'Teacher')
    teachers = Teacher.objects.all()

    for teacher in teachers:
        if teacher.published and teacher.status != 4:
            teacher.published = False
            teacher.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0101_weixintoken'),
    ]

    operations = [
        migrations.RunPython(unpublished_test_teacher),
    ]
