# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0102_unpublished_test_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
