# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0103_weixintoken_expires_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='weixintoken',
            name='jsapi_ticket',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='weixintoken',
            name='jsapi_ticket_life',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weixintoken',
            name='jsapi_ticket_new_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
