# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0103_weixintoken_expires_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='weixintoken',
            name='token_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'access_token'), (2, 'jsapi_ticket')], null=True),
        ),
    ]
