# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0104_auto_20160308_2026'),
        ('app', '0106_timeslot_suspended'),
    ]

    operations = [
    ]
