# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0107_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelrecord',
            name='operation',
            field=models.CharField(choices=[('d', '降级'), ('u', '升级'), ('b', '成为')], default='u', max_length=1),
        ),
    ]
