# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 04:10
from __future__ import unicode_literals

from django.db import migrations, models


def add_withdraw_weekday(apps, schema_editor):
    WithdrawWeekday = apps.get_model('app', 'WithdrawWeekday')

    ww = WithdrawWeekday(weekday=2)
    ww.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0109_add_level_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawWeekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveIntegerField(default=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(add_withdraw_weekday),
    ]
