# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 06:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0110_teacher_status_confirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(choices=[('ic', '补填资料'), ('pr', '初选淘汰'), ('pp', '邀约面试'), ('ir', '面试失败'), ('ip', '面试通过')], max_length=3)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
