# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0111_auto_20160311_1441'),
        ('app', '0111_auditrecord'),
    ]

    operations = [
    ]
