# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0113_auto_20160312_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
