# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-14 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0114_auto_20160312_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklytimeslot',
            options={'ordering': ['weekday', 'start', 'end']},
        ),
    ]
