# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-15 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0116_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_id', models.CharField(max_length=27, unique=True)),
                ('order_no', models.CharField(max_length=27)),
                ('amount', models.IntegerField(default=0)),
                ('succeed', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=10)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('time_succeed', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('failure_code', models.CharField(max_length=10)),
                ('failure_msg', models.CharField(max_length=30)),
                ('metadata', models.CharField(max_length=50)),
                ('transaction_no', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='charge',
            name='body',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='charge',
            name='client_ip',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='charge',
            name='currency',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='charge',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='charge',
            name='subject',
            field=models.CharField(max_length=32),
        ),
        migrations.AddField(
            model_name='refund',
            name='charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Charge'),
        ),
    ]
