# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-15 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0117_auto_20160315_1747'),
        ('app', '0117_auto_20160315_1659'),
    ]

    operations = [
    ]
