# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0118_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='accounthistory',
            name='bankcard',
        ),
        migrations.RemoveField(
            model_name='accounthistory',
            name='done',
        ),
        migrations.RemoveField(
            model_name='accounthistory',
            name='done_at',
        ),
        migrations.RemoveField(
            model_name='accounthistory',
            name='done_by',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='account',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='submit_time',
        ),
        migrations.AddField(
            model_name='accounthistory',
            name='valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accounthistory',
            name='timeslot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.TimeSlot'),
        ),
        migrations.AlterField(
            model_name='accounthistory',
            name='withdrawal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Withdrawal'),
        ),
    ]
