# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0120_auto_20160317_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounthistory',
            options={'ordering': ['-submit_time']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='orderrefundrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['-start', '-created_at']},
        ),
    ]
