# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-23 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0125_timeslotchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcard',
            name='opening_bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bankcard',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Region'),
        ),
    ]
