# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-23 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0126_auto_20160323_1558'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='timeslot',
            index_together=set([('start', 'created_at')]),
        ),
    ]
