# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-23 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0127_auto_20160323_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={},
        ),
        migrations.AlterIndexTogether(
            name='timeslot',
            index_together=set([]),
        ),
    ]
