# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0128_auto_20160323_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='desc_content',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='desc_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
