# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


def copy_policy(apps, schema_editor):
    Policy = apps.get_model('app', 'Policy')
    StaticContent = apps.get_model('app', 'StaticContent')

    queryset = Policy.objects.all()
    for ply in queryset:
        stcontent = StaticContent(name='policy', content=ply.content)
        stcontent.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0131_staticcontent_updated_at'),
    ]

    operations = [
        migrations.RunPython(copy_policy),
    ]
