# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0131_staticcontent_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticcontent',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
