# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0134_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='status',
            field=models.CharField(choices=[('ep', '待处理'), ('es', '已安排时间'), ('ec', '已完成测评')], default='ep', max_length=2),
        ),
    ]
