# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0140_add_test_user_into_group'),
        ('app', '0138_staffpermission'),
    ]

    operations = [
    ]
