# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0142_change_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='old_student_name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='old_student_school_name',
        ),
    ]
