# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0144_profile_klx_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='klx_password',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
