# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0144_timeslot_reminded'),
        ('app', '0145_profile_klx_password'),
    ]

    operations = [
    ]
