# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0145_coupon_reminded'),
        ('app', '0146_merge'),
    ]

    operations = [
    ]
