# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0147_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='mini_total_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupongenerator',
            name='mini_total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
