# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0155_auto_20160802_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='imported',
            field=models.BooleanField(default=False),
        ),
    ]
