# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0156_teacher_imported'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='imported',
            field=models.BooleanField(default=False),
        ),
    ]
