# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 09:56
from __future__ import unicode_literals

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0158_profile_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=app.models.CharNullField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
    ]
