# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-19 09:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0163_priceconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolIncomeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('p', '待处理'), ('a', '已通过'), ('r', '被驳回')], default='p', max_length=2)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('remark', models.CharField(blank=True, max_length=300, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SchoolAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
