# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-19 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0164_schoolincomerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolincomerecord',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='schoolincomerecord',
            name='start_date',
        ),
    ]
