# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0166_schoolincomerecord_income_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklytimeslot',
            unique_together=set([]),
        ),
    ]
