# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-18 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0169_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='lecturers')),
                ('phone', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('introduce', models.CharField(blank=True, max_length=500, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_assistant',
            field=models.BooleanField(default=False),
        ),
    ]
