# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-18 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0171_livecourseweeklytimeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Teacher')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ClassRoom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiveCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_no', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=20)),
                ('grade_desc', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('fee', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiveCourseTimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('live_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LiveCourse')),
            ],
            options={
                'ordering': ['-start', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lecturer',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='livecourse',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Lecturer'),
        ),
        migrations.AddField(
            model_name='livecourse',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Subject'),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='live_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LiveCourse'),
        ),
    ]
