# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-25 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0173_livecourse_period_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='live_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.LiveClass'),
        ),
        migrations.AlterField(
            model_name='order',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Grade'),
        ),
    ]
