# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-26 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0174_auto_20161025_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.School'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Subject'),
        ),
        migrations.AlterField(
            model_name='order',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Teacher'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weekly_time_slots',
            field=models.ManyToManyField(blank=True, to='app.WeeklyTimeSlot'),
        ),
    ]
