# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-08 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0175_auto_20161026_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='share_rate',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='schoolincomerecord',
            name='type',
            field=models.CharField(choices=[('1', '一对一'), ('l', '双师直播')], default='1', max_length=2),
        ),
    ]
