# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-13 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0177_lecturer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Subject'),
        ),
    ]
