# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-20 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0179_auto_20161220_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_set', to='app.QuestionOption'),
        ),
    ]
