# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-21 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0180_auto_20161220_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='pad_token',
            field=models.CharField(default='invalid_token', max_length=100),
        ),
    ]
