# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-30 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0181_parent_pad_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='pad_token',
            field=models.CharField(db_index=True, default='invalid_token', max_length=100),
        ),
    ]
