# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-03 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0182_auto_20161230_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('live_course_timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LiveCourseTimeSlot')),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.QuestionGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ExerciseSession')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.QuestionOption')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Parent')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
