# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-05 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0183_exercisesession_exercisesubmit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionoption',
            options={'ordering': ['pk']},
        ),
    ]
