# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-27 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0184_auto_20170505_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='livecoursetimeslot',
            name='mistakes_pushed',
            field=models.BooleanField(default=False),
        ),
    ]
