# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-03 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0187_schoolincomerecordv2'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrefundrecord',
            name='completed_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderrefundrecord',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderrefundrecord',
            name='finish_lessons',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderrefundrecord',
            name='hour_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderrefundrecord',
            name='on_the_lesson_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderrefundrecord',
            name='refund_lessons',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderrefundrecord',
            name='remaining_lessons',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderrefundrecord',
            name='total_lessons',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
